### ISSUE TITLE
Text size of main description.

### ISSUE THREAD

**Issue by FiGOBLAC** [reduxframework/docs#1]
I think this is gorgeous... The descriptions for each section are so easy to articulate. I don't have that many issues articulating the current documentation but this makes it easy for me to take a look at something with one pass and grasp how it supposed to work and get right back to work instead of spending too much time trying to examine the example to understand the appropriate way to use the code. I do have one humble suggestion..  At times the text size for the descriptions and the description's title don't appear to have much of a contrast. The text size of the description could probably be a bit smaller. For example in the following sections:

**Select a Unique opt_name**
**Redux is built to allow multiple projects to use Redux at once. You must select a unique opt_name to avoid avoid collision with other projects. Make sure you choose something that's not too common. Oh, and no spaces**.  

And:

**Creating a Redux Instance**
**Creating a Redux instance is pretty simple.**

The title and description for these sections almost appear to be the same size. I think its way better for the eyes and will make it much easier to quickly recognize a section if the contrast was a little more apparent.

**Comment by KhaledaBegum** [comment]
Health city24.com

**Comment by dovy** [comment]
@FiGOBLAC check it out now. Completely new site.
