### ISSUE TITLE
wordpress.org-submissions

### ISSUE THREAD

**Issue by kprovance** [reduxframework/docs#12]
`
A developer can then delete the tracking class and be fully compliant with 
WordPress.org requirements. That class is located in: `~/ReduxCore/inc/classes/tracking.php`.
`

Obviously this was moved or split up.  Where is it now, specifically?  Can this even be removed anymore in this fashion?

**Comment by dovy** [comment]
Oy. Do we need to provide the remove tracking hook? I'll look into it.

**Comment by kprovance** [comment]
We could?  If folks know about it, they want begin using it more then we'd like?  It's your baby.  Whatever you think is best.  ;-)

**Comment by dovy** [comment]
Updated a little. Still need to add the theme-check args.
