### ISSUE TITLE
Deprecated article - Updating a CSS File Dynamically

### ISSUE THREAD

**Issue by kprovance** [reduxframework/docs#13]
~~Advanced: Typography Preview w/ Local Fonts~~ Deleted
Advanced: Updating a CSS File Dynamically

These no longer work.  They should be removed.  We've been asked to support the filesystem article about dynamic css files more than once.  I would not even include it anymore, even with a deprecated notice, because folks don;t read that part and will still ask, and we'll still have to say no.

**Comment by dovy** [comment]
So I agree (and deleted) the typography guide since Custom Fonts in Pro will resolve this.

The updating a CSS file dynamically, I think we need to rework and keep in some way. It's a common ask and I want to provide at least a launch point. Thoughts?

**Comment by kprovance** [comment]
I really don't want to support it when people can;t figure it out.  So...add a note that says 'this code is 'as is' and 'such methods of dynamic CSS may slow down the panel and site...why not use 'output' instead?;  As long as folks understand the risks and that we don't support it.  It would be...a courtesy thing?  Most people go to 'output' after I explain it to them.  I also balk because writing dynamic CSS is not the best practice.  Another complaint is 'nothing written until I save', which as you may recall is why we dropped SCSS in the core.  It was too damn messy and it slowed everything down.

**Comment by dovy** [comment]
So could you take a stab at doing it properly?

**Comment by kprovance** [comment]
Last time we talked about it we agreed that dynamic CSS file creation was a bad idea.

**Comment by dovy** [comment]
Deleted.
