### ISSUE TITLE
Redux 4 Global Argument Error

### ISSUE THREAD

**Issue by themecatinfo** [reduxframework/docs#19]
Hi team redux,

I have found an error on the global argument database ( theme_mods, theme_mods_expanded ).
When I add the database like theme_mods or theme_mods_expended, I have found an error on saving of redux options and error is Ajax:warning. 
And here is the errors list by actions.

PHP Warning:  Illegal offset type in ReduxCore\framework.php on line 661.
PHP Stack trace:
PHP   1. {main}() wp-admin\admin-ajax.php:0
PHP   2. do_action() wp-admin\admin-ajax.php:173
PHP   3. WP_Hook->do_action() wp-includes\plugin.php:465
PHP   4. WP_Hook->apply_filters() wp-includes\class-wp-hook.php:310
PHP   5. Redux_AJAX_Save->save() wp-includes\class-wp-hook.php:286
PHP   6. Redux_Options->validate_options() ReduxCore\inc\classes\class-redux-ajax-save.php:80
PHP   7. ReduxFramework->set() ReduxCore\inc\classes\class-redux-options.php:923

This error was so hard to find out for me. Because, I thought that error is in my PHP code. So, I sorted my PHP so many times. Before this ticket, I created a ticket, name by Dismisions Field Type Error and after realize that error is not in this field, I close the ticket.

**Comment by dovy** [comment]
Hey, could you post on the repo for the version of Redux you're using? This is the Doc site.

https://github.com/reduxframework/redux-framework = Redux 3.x
https://github.com/reduxframework/redux-framework-4 = Redux 4.x

**Comment by themecatinfo** [comment]
> Hey, could you post on the repo for the version of Redux you're using? This is the Doc site.
> 
> https://github.com/reduxframework/redux-framework = Redux 3.x
> https://github.com/reduxframework/redux-framework-4 = Redux 4.x

Sorry I got it.
