### ISSUE TITLE
Docs wrong with 4.x Migration & Compatibility

### ISSUE THREAD

**Issue by mtaman** [reduxframework/docs#36]
###  **4.x Migration & Compatibility**
https://docs.redux.io/guides/other/migration-guide.html

v 3.x = 
in doc is 

Redux::setSections
--
but not work it is 

Redux::setSection
--
v 4 =
Redux::set_sections
Not work 

Right Redux::setSection Not Redux::set_sections

**Comment by dovy** [comment]
Resolved through education.  ;)
