### ISSUE TITLE
Composer Package Incorrect?

### ISSUE THREAD

**Issue by KuroTsuto** [reduxframework/docs#37]
I recently tried to `composer require reduxframework/redux-framework` as described in [/docs/guides/basics/install.md](https://github.com/reduxframework/docs/blob/master/docs/guides/basics/install.md), however Composer was unable to locate the package.

A search on Packagist only brings up [`redux-framework/redux-framework`](https://packagist.org/packages/redux-framework/redux-framework).

Is the documentation incorrect, or have I overlooked something?

**Comment by dovy** [comment]
Ooo, good catch. Looks like packagist now has the proper name. Just use what you expect, you were correct.  :)

**Comment by dovy** [comment]
P.S. I updated the docs to reflect this.  ;)
