### ISSUE TITLE
default not working on type select

### ISSUE THREAD

**Issue by CupCodeIr** [reduxframework/docs#63]
I'm using Redux Framework 4.1.24 and I noticed that `default` attribute doesn't work on input type `select`
![image](https://user-images.githubusercontent.com/64161399/156021382-f7b34347-282e-4c0d-b7a0-0e0d8cf01587.png)
![image](https://user-images.githubusercontent.com/64161399/156021578-4854a219-76a8-4482-99b5-226618013e4d.png)

**Comment by kprovance** [comment]
Use `options` instead of `data`.  The data argument is for something else.  http://devs.redux.io/core-fields/select.html

Also, this repo is for the docs site.  This question is better suited toward the redux-framework repo.
