### ISSUE TITLE
Metabox extension (editor) not working

### ISSUE THREAD

**Issue by Spartak-rnd** [reduxframework/docs#65]
Hi.
I installed the metabox extension for posts, the metabox with the editor field does not work in visual mode, only TXT.
When   disable gutenberg, it works.
I wanted to leave Gutenberg,  + put wp_editor for the metabox, is it possible? What needs to be fixed?
WP 6.0
Redux Framework  4.3
Theme - default

Thanks

**Comment by kprovance** [comment]
`I installed the metabox extension for posts`

This implies you're still using the individual extension. Metaboxes is now part of the Redux core. Any version of the extension is outdated, which is likely the problem.  The version of Metaboxes included with Redux does not appear to have this issue. I just checked.

Also, this is not supported for Redux. This is for our docs.
