### ISSUE TITLE
Metaboxes rewrite

### ISSUE THREAD

**Issue by dovy** [reduxframework/docs#9]
Need to do the markdown conversion for each. These were previously done in HTML. Various errors exist specifically with date-time-picker, multi-media, repeater, and social-profiles.

- [x] Accordion
- [x] CodeMirror - Advanced Code Editor
- [x] Color Schemes
- [x] CSS Layout
- [x] Custom Fonts
- [x] Google Maps
- [x] Date-Time Picker
- [x] Icon Select
- [x] JS Button
- [ ] Metaboxes
- [x] Multi Media
- [x] Repeater
- [x] Social Profiles
- [x] Taxonomy

**Comment by dovy** [comment]
The rest is yours Kevin.  ;)

**Comment by dovy** [comment]
Went through and did it all. I'm going to take a stab at a rewrite for Metaboxes.

**Comment by imadeelnazar** [comment]
Redux_Metaboxes::set_box 

repeater field not showing the add more button is there anything you suggest me to do to fix that?
