### ISSUE TITLE
Repeater with editor don't save text.

### ISSUE THREAD

**Issue by TarasiukDima** [reduxframework/docs#91]
If I write text in the visual editor and click save, after the page is reloaded, the text appears old (before saving). In the ajax response, I get the text unchanged.
If I click on the text tab and then write the text, the ajax response contains a new text.

Example field.
````php
 array(
        'id'          => 'pref_questions',
        'type'        => 'repeater',
        'title'       => esc_html__('Questions', 'theme_name'),
        'limit'       => 20,
        'full_width'  => true,
        'item_name'   => '',
        'sortable'    => true,
        'collapsible' => false,
        'fields'      => array(
          array(
            'id'       => 'pref_questions_title',
            'type'     => 'textarea',
            'rows'     => 2,
            'title'    => esc_html__('Question', 'theme_name'),
          ),
          array(
            'id'       => 'pref_questions_answer',
            'type'     => 'editor',
            'title'    => esc_html__('Answer', 'theme_name'),
            'args'   => array(
              'textarea_rows' => 12,
              'teeny'         => true,
              'wpautop'       => true,
              'media_buttons' => false,
            )
          ),
        ),
      ),
      ```
````

**Comment by kprovance** [comment]
This is the incorrect forum to post this issue. Also, there is not enough information.  Please visit here:  https://github.com/reduxframework/redux-framework/issues/new/choose

If you are a theme developer or user, you must pick the correct choice. Please make sure to read ALL the text provided and include ALL the requested information. If it's not provided, we won't be able to assist.
