### ISSUE TITLE
reading 'mceInit' 

### ISSUE THREAD

**Issue by ahmadrz1379** [reduxframework/docs#96]
i create a repeater but when i wanna add a item to reapter in wp-admin i recive this error and field not added how to fix it

Uncaught TypeError: Cannot read properties of undefined (reading 'mceInit')
<?php
Redux::set_section(
    $opt_name,
    [
        'title' => 'header contents',
        'id' => 'header',
        'icon' => 'el el-header',
        'fields' => [
            [
                'id' => 'dropdown_headers',
                'type' => 'repeater',
                'group_values' => true,
                'title' => 'drop down urls ',
                'fields' => [
                    [
                        'id' => 'dropdown_title',
                        'type' => 'text',
                        'title' => 'title'
                    ],
                    [
                        'id' => 'dropdown_url',
                        'type' => 'text',
                        'title' => 'url '
                    ],

                ]

if (!class_exists('Redux')) {
    return;
}
Redux::disable_demo();
$opt_name = 'theme_settings';

$theme = wp_get_theme(); // For use with some settings. Not necessary.

$args = [
    'display_name' => $theme->get('Name'),
    'display_version' => $theme->get('Version'),
    'menu_title' => 'asdfasf',
    'customizer' => true,
];

Redux::set_args($opt_name, $args);

include_once get_template_directory() . '/settings/sections/header.php';

Redux::init($opt_name);

**Comment by kprovance** [comment]
You're on the repository. This is for the docs site. What you want is here: https://github.com/reduxframework/redux-framework/issues/4037

We're aware of it and working on it.
